import React from "react"
// import Head from "next/head"
// import Image from "next/image"
// import styles from "../styles/Home.module.css"

import CardsList from "./CardsList"
// import CardForm from "./CardForm"
// import Viewer from "./Viewer"

export default function Home() {
  return <CardsList />
}

// export default function Home() {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <CardsList />

//         {/* <hr /> */}

//         {/* <Viewer /> */}

//         {/* <CardForm /> */}

//         {/* <div className={styles.grid}>
//           <a
//             href="https://github.com/vercel/next.js/tree/master/examples"
//             className={styles.card}
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>
//         </div> */}
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{" "}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }
